apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-app-deployment
  labels:
    env: dev
spec:
  selector:
    matchLabels:
      app: dev-app
  template:
    metadata:
      labels:
        app: dev-app
    spec:
      containers:
        - name: my-app-container
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 80
